// تمام سکتورهای Style Manager شما اینجاست
const styleSectors = [
  {
    name: '📐 ابعاد و فاصله',
    open: true,
    properties: [
      {
        name: 'عرض',
        property: 'width',
        type: 'select',
        defaults: 'auto',
        list: [
          { value: 'auto', name: 'خودکار' },
          { value: '100%', name: '100%' },
          { value: '75%', name: '75%' },
          { value: '50%', name: '50%' },
          { value: '25%', name: '25%' },
        ],
      },
      {
        name: 'ارتفاع',
        property: 'height',
        type: 'select',
        defaults: 'auto',
        list: [
          { value: 'auto', name: 'خودکار' },
          { value: '100px', name: '100 پیکسل' },
          { value: '200px', name: '200 پیکسل' },
          { value: '300px', name: '300 پیکسل' },
          { value: '400px', name: '400 پیکسل' },
        ],
      },
      {
        name: 'فاصله داخلی',
        property: 'padding',
        type: 'composite',
        properties: [
          { name: 'بالا', property: 'padding-top', type: 'integer', units: ['px'], defaults: '0' },
          { name: 'راست', property: 'padding-right', type: 'integer', units: ['px'], defaults: '0' },
          { name: 'پایین', property: 'padding-bottom', type: 'integer', units: ['px'], defaults: '0' },
          { name: 'چپ', property: 'padding-left', type: 'integer', units: ['px'], defaults: '0' },
        ],
      },
      {
        name: 'فاصله خارجی',
        property: 'margin',
        type: 'composite',
        properties: [
          { name: 'بالا', property: 'margin-top', type: 'integer', units: ['px'], defaults: '0' },
          { name: 'راست', property: 'margin-right', type: 'integer', units: ['px'], defaults: '0' },
          { name: 'پایین', property: 'margin-bottom', type: 'integer', units: ['px'], defaults: '0' },
          { name: 'چپ', property: 'margin-left', type: 'integer', units: ['px'], defaults: '0' },
        ],
      },
    ],
  },
  {
    name: '✍️ تنظیمات متن',
    open: true,
    properties: [
      {
        name: 'اندازه فونت',
        property: 'font-size',
        type: 'select',
        defaults: '16px',
        list: [
          { value: '12px', name: '12px - خیلی کوچک' },
          { value: '14px', name: '14px - کوچک' },
          { value: '16px', name: '16px - معمولی' },
          { value: '18px', name: '18px - متوسط' },
          { value: '20px', name: '20px - بزرگ' },
          { value: '24px', name: '24px - خیلی بزرگ' },
          { value: '32px', name: '32px - عنوان' },
          { value: '48px', name: '48px - عنوان بزرگ' },
        ],
      },
      {
        name: 'ضخامت فونت',
        property: 'font-weight',
        type: 'select',
        defaults: '400',
        list: [
          { value: '300', name: 'نازک' },
          { value: '400', name: 'معمولی' },
          { value: '500', name: 'متوسط' },
          { value: '600', name: 'نیمه‌بولد' },
          { value: '700', name: 'بولد' },
          { value: '800', name: 'خیلی بولد' },
        ],
      },
      { name: 'رنگ متن', property: 'color', type: 'color', defaults: '#333333' },
      {
        name: 'تراز متن',
        property: 'text-align',
        type: 'radio',
        defaults: 'right',
        list: [
          { value: 'right', title: 'راست' },
          { value: 'center', title: 'وسط' },
          { value: 'left', title: 'چپ' },
          { value: 'justify', title: 'جاستیفای' },
        ],
      },
      {
        name: 'تزیین متن',
        property: 'text-decoration',
        type: 'select',
        defaults: 'none',
        list: [
          { value: 'none', name: 'بدون تزیین' },
          { value: 'underline', name: 'خط زیر' },
          { value: 'line-through', name: 'خط خورده' },
          { value: 'overline', name: 'خط بالا' },
        ],
      },
      {
        name: 'شیب متن',
        property: 'font-style',
        type: 'select',
        defaults: 'normal',
        list: [
          { value: 'normal', name: 'عادی' },
          { value: 'italic', name: 'کج (Italic)' },
          { value: 'oblique', name: 'شیب‌دار' },
        ],
      },
      {
        name: 'فاصله خطوط',
        property: 'line-height',
        type: 'select',
        defaults: '1.5',
        list: [
          { value: '1', name: '1 - فشرده' },
          { value: '1.2', name: '1.2' },
          { value: '1.5', name: '1.5 - معمولی' },
          { value: '1.8', name: '1.8' },
          { value: '2', name: '2 - گشاد' },
          { value: '2.5', name: '2.5 - خیلی گشاد' },
        ],
      },
      { name: 'فاصله حروف', property: 'letter-spacing', type: 'integer', units: ['px'], defaults: '0', min: -5, max: 20 },
    ],
  },
  {
    name: '🎨 پس‌زمینه',
    open: false,
    properties: [
      { name: 'رنگ پس‌زمینه', property: 'background-color', type: 'color', defaults: 'transparent' },
      { name: 'تصویر پس‌زمینه', property: 'background-image', type: 'file', defaults: 'none' },
      {
        name: 'اندازه پس‌زمینه',
        property: 'background-size',
        type: 'select',
        defaults: 'cover',
        list: [
          { value: 'auto', name: 'خودکار' },
          { value: 'cover', name: 'پوشش کامل' },
          { value: 'contain', name: 'نمایش کامل' },
        ],
      },
      {
        name: 'موقعیت پس‌زمینه',
        property: 'background-position',
        type: 'select',
        defaults: 'center center',
        list: [
          { value: 'top left', name: 'بالا چپ' },
          { value: 'top center', name: 'بالا وسط' },
          { value: 'top right', name: 'بالا راست' },
          { value: 'center left', name: 'وسط چپ' },
          { value: 'center center', name: 'وسط وسط' },
          { value: 'center right', name: 'وسط راست' },
          { value: 'bottom left', name: 'پایین چپ' },
          { value: 'bottom center', name: 'پایین وسط' },
          { value: 'bottom right', name: 'پایین راست' },
        ],
      },
    ],
  },
  {
    name: '🔲 حاشیه و سایه',
    open: false,
    properties: [
      {
        name: 'گردی گوشه‌ها',
        property: 'border-radius',
        type: 'select',
        defaults: '0px',
        list: [
          { value: '0px', name: 'بدون گردی' },
          { value: '4px', name: '4px - کم' },
          { value: '8px', name: '8px - متوسط' },
          { value: '12px', name: '12px - زیاد' },
          { value: '16px', name: '16px - خیلی زیاد' },
          { value: '50%', name: '50% - دایره' },
        ],
      },
      {
        name: 'حاشیه',
        property: 'border',
        type: 'composite',
        properties: [
          { name: 'عرض', property: 'border-width', type: 'integer', units: ['px'], defaults: '0' },
          {
            name: 'نوع',
            property: 'border-style',
            type: 'select',
            defaults: 'solid',
            list: [
              { value: 'none', name: 'ندارد' },
              { value: 'solid', name: 'خط پیوسته' },
              { value: 'dashed', name: 'خط چین' },
              { value: 'dotted', name: 'نقطه چین' },
            ],
          },
          { name: 'رنگ', property: 'border-color', type: 'color', defaults: '#000000' },
        ],
      },
      {
        name: 'سایه جعبه',
        property: 'box-shadow',
        type: 'select',
        defaults: 'none',
        list: [
          { value: 'none', name: 'بدون سایه' },
          { value: '0 1px 3px rgba(0,0,0,0.1)', name: 'سایه کم' },
          { value: '0 4px 6px rgba(0,0,0,0.1)', name: 'سایه متوسط' },
          { value: '0 10px 25px rgba(0,0,0,0.15)', name: 'سایه زیاد' },
          { value: '0 20px 40px rgba(0,0,0,0.2)', name: 'سایه خیلی زیاد' },
        ],
      },
    ],
  },
  {
    name: '📍 موقعیت و نمایش',
    open: false,
    properties: [
      {
        name: 'نوع نمایش',
        property: 'display',
        type: 'select',
        defaults: 'block',
        list: [
          { value: 'block', name: 'بلوکی' },
          { value: 'inline-block', name: 'درون خطی-بلوکی' },
          { value: 'inline', name: 'درون خطی' },
          { value: 'flex', name: 'فلکس' },
          { value: 'grid', name: 'گرید' },
          { value: 'none', name: 'مخفی' },
        ],
      },
      {
        name: '🎯 قرارگیری در صفحه',
        property: 'margin',
        type: 'radio',
        defaults: '',
        list: [
          { value: '0 auto', name: 'وسط صفحه 🎯', title: 'وسط افقی' },
          { value: '0', name: 'پیش‌فرض', title: 'حالت عادی' },
          { value: '0 0 0 auto', name: 'سمت چپ', title: 'چپ صفحه' },
          { value: '0 auto 0 0', name: 'سمت راست', title: 'راست صفحه' },
        ],
      },
      {
        name: 'موقعیت',
        property: 'position',
        type: 'select',
        defaults: 'static',
        list: [
          { value: 'static', name: 'استاتیک' },
          { value: 'relative', name: 'نسبی' },
          { value: 'absolute', name: 'مطلق' },
          { value: 'fixed', name: 'ثابت' },
          { value: 'sticky', name: 'چسبان' },
        ],
      },
      { name: 'شفافیت', property: 'opacity', type: 'slider', defaults: '1', min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    name: '🎯 تراز و چیدمان',
    open: false,
    properties: [
      {
        name: 'تراز افقی محتوا',
        property: 'justify-content',
        type: 'radio',
        defaults: 'flex-start',
        list: [
          { value: 'flex-start', name: 'راست', title: 'راست' },
          { value: 'center', name: 'وسط', title: 'وسط' },
          { value: 'flex-end', name: 'چپ', title: 'چپ' },
          { value: 'space-between', name: 'فاصله بین', title: 'فاصله یکسان بین' },
          { value: 'space-around', name: 'فاصله دور', title: 'فاصله دور المان‌ها' },
        ],
      },
      {
        name: 'تراز عمودی محتوا',
        property: 'align-items',
        type: 'radio',
        defaults: 'stretch',
        list: [
          { value: 'flex-start', name: 'بالا', title: 'بالا' },
          { value: 'center', name: 'وسط', title: 'وسط' },
          { value: 'flex-end', name: 'پایین', title: 'پایین' },
          { value: 'stretch', name: 'کشیده', title: 'کشیده شده' },
        ],
      },
      {
        name: 'تراز متن',
        property: 'text-align',
        type: 'radio',
        defaults: 'right',
        list: [
          { value: 'right', title: 'راست' },
          { value: 'center', title: 'وسط' },
          { value: 'left', title: 'چپ' },
          { value: 'justify', title: 'جاستیفای' },
        ],
      },
    ],
  },
];

export default styleSectors;
